pipeline {
   agent any
   environment {
       OPENSHIFT_PROJECT = 'your_project_name'
       OPENSHIFT_APP_NAME = 'salesforce-domain-builder'
       OPENSHIFT_ROUTE_HOST = 'your_route_host'
       OPENSHIFT_IMAGE_NAME = 'salesforce-domain-builder-image'
       OPENSHIFT_IMAGE_TAG = 'latest'
   }
   stages {
       stage('checkout') {
           steps {
               checkout scm
           }
       }
       stage('Build image') {
           steps {
               script {
                   openshift.withCluster() {
                       openshift.withProject(env.OPENSHIFT_PROJECT) {
                           def dockerImage = docker.build("${env.OPENSHIFT_IMAGE_NAME}:${env.OPENSHIFT_IMAGE_TAG}", '.')
                           dockerImage.push()
                       }
                   }
               }
           }
       }
       stage('Deploy to OpenShift') {
           steps {
               script {
                   openshift.withCluster() {
                       openshift.withProject(env.OPENSHIFT_PROJECT) {
                           openshift.newApp("${env.OPENSHIFT_IMAGE_NAME}:${env.OPENSHIFT_IMAGE_TAG}",
                                           "--name=${env.OPENSHIFT_APP_NAME}",
                                           "--hostname=${env.OPENSHIFT_ROUTE_HOST}")
                       }
                   }
               }
           }
       }
   }
}
